using BIS.PAA;
using GameRealisticMap.Arma3.Assets;
using GameRealisticMap.Arma3.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

namespace GameRealisticMap.Arma3
{
    public static class SatMapFromIdMapGenerator
    {
        /// <summary>
        /// Rebuilds a satmap from the id map, matching the soft look of the map generated by GRM:
        /// each surface is filled with the low-resolution (8px) tile of its real game ground
        /// texture, then the whole image is Gaussian-blurred so surfaces blend smoothly instead of
        /// showing hard tiled edges. Without a file system it falls back to the flat average color.
        /// </summary>
        public static void Generate(string idMapFile, string satMapFile, TerrainMaterialLibrary library, IProgress<double>? progress = null,
            IGameFileSystem? gameFileSystem = null, double idmapMetersPerPixel = 1.0, double metersPerTextureRepeat = 0)
        {
            using var idMap = Image.Load<Rgba32>(idMapFile);
            using var satMap = new Image<Rgba32>(idMap.Width, idMap.Height);

            var tiles = new Dictionary<Rgba32, Image<Rgba32>?>();
            var flatColors = new Dictionary<Rgba32, Rgba32>();

            foreach (var definition in library.Definitions)
            {
                var material = definition.Material;
                var idColor = new Rgba32(material.Id.R, material.Id.G, material.Id.B, 255);
                if (tiles.ContainsKey(idColor))
                {
                    continue;
                }
                var tile = LoadColorTile(material, gameFileSystem);
                tiles[idColor] = tile;
                flatColors[idColor] = tile != null ? AverageColor(tile) : new Rgba32(128, 128, 128, 255);
            }

            for (int y = 0; y < idMap.Height; y++)
            {
                for (int x = 0; x < idMap.Width; x++)
                {
                    var idPixel = idMap[x, y];
                    idPixel.A = 255;

                    if (!tiles.TryGetValue(idPixel, out var tile))
                    {
                        // Unknown id color: snap to the nearest known surface and cache it
                        var nearest = FindNearestKey(tiles.Keys, idPixel);
                        tile = tiles[nearest];
                        tiles[idPixel] = tile;
                        flatColors[idPixel] = flatColors[nearest];
                    }

                    // Tile the small texture natively (soft color with slight natural variation)
                    satMap[x, y] = tile != null
                        ? tile[x % tile.Width, y % tile.Height]
                        : flatColors[idPixel];
                }

                if (progress != null && y % 200 == 0)
                {
                    progress.Report((double)y / idMap.Height * 0.9);
                }
            }

            // Blend surfaces together for the soft map look (same as the generated fake satmap)
            satMap.Mutate(d => d.GaussianBlur(1.5f));
            progress?.Report(1.0);

            satMap.Save(satMapFile);

            foreach (var tile in tiles.Values)
            {
                tile?.Dispose();
            }
        }

        private static Image<Rgba32>? LoadColorTile(TerrainMaterial material, IGameFileSystem? gameFileSystem)
        {
            var colorTexture = material.ColorTexture;
            if (gameFileSystem == null || string.IsNullOrEmpty(colorTexture) || colorTexture.Contains("{PboPrefix}"))
            {
                return material.FakeSatPngImage != null ? Image.Load<Rgba32>(material.FakeSatPngImage) : null;
            }
            try
            {
                using var stream = gameFileSystem.OpenFileIfExists(colorTexture);
                if (stream == null)
                {
                    return material.FakeSatPngImage != null ? Image.Load<Rgba32>(material.FakeSatPngImage) : null;
                }
                using var seekable = new MemoryStream();
                stream.CopyTo(seekable);
                seekable.Position = 0;
                var paa = new PAA(seekable);
                // Use the small mipmap: soft downsampled color with a bit of natural variation,
                // exactly like the fake satmap render (avoids hard, repetitive tiling)
                var mip = paa.Mipmaps.OrderBy(m => Math.Abs(m.Width - 8)).First();
                var pixels = PAA.GetARGB32PixelData(paa, seekable, mip);
                return Image.LoadPixelData<Bgra32>(pixels, mip.Width, mip.Height).CloneAs<Rgba32>();
            }
            catch
            {
                return material.FakeSatPngImage != null ? Image.Load<Rgba32>(material.FakeSatPngImage) : null;
            }
        }

        private static Rgba32 AverageColor(Image<Rgba32> tile)
        {
            long r = 0, g = 0, b = 0;
            var count = 0;
            for (int y = 0; y < tile.Height; y++)
            {
                for (int x = 0; x < tile.Width; x++)
                {
                    var p = tile[x, y];
                    r += p.R; g += p.G; b += p.B;
                    count++;
                }
            }
            if (count == 0) return new Rgba32(128, 128, 128, 255);
            return new Rgba32((byte)(r / count), (byte)(g / count), (byte)(b / count), 255);
        }

        private static Rgba32 FindNearestKey(IEnumerable<Rgba32> keys, Rgba32 pixel)
        {
            Rgba32 nearest = new Rgba32(128, 128, 128);
            int minDistance = int.MaxValue;
            foreach (var key in keys)
            {
                int rDiff = key.R - pixel.R;
                int gDiff = key.G - pixel.G;
                int bDiff = key.B - pixel.B;
                int distance = rDiff * rDiff + gDiff * gDiff + bDiff * bDiff;
                if (distance < minDistance)
                {
                    minDistance = distance;
                    nearest = key;
                }
            }
            return nearest;
        }
    }
}
