using System.Text;
using GameRealisticMap.Arma3;

namespace GameRealisticMap.Reforger
{
    internal static class ReforgerReadme
    {
        public static string Create(Arma3MapConfig config, ReforgerExportStats stats)
        {
            var sb = new StringBuilder();

            sb.AppendLine(FormattableString.Invariant($"# {config.WorldName} - Arma Reforger export"));
            sb.AppendLine();
            sb.AppendLine("Generated by Game Realistic Map. Import these files into the Enfusion World Editor");
            sb.AppendLine("(Arma Reforger Tools). Reforger worlds cannot be binarized outside the Workbench, so");
            sb.AppendLine("this is an import pack, not a ready-to-play mod.");
            sb.AppendLine();

            sb.AppendLine("## Terrain size");
            sb.AppendLine();
            sb.AppendLine(FormattableString.Invariant($"- Terrain size : {config.SizeInMeters} x {config.SizeInMeters} m"));
            sb.AppendLine(FormattableString.Invariant($"- Grid         : {config.TerrainArea.GridSize} x {config.TerrainArea.GridSize} cells"));
            sb.AppendLine(FormattableString.Invariant($"- Cell size    : {config.TerrainArea.GridCellSize} m"));
            sb.AppendLine(FormattableString.Invariant($"- Imagery res. : {config.Resolution} m/px"));
            sb.AppendLine();

            sb.AppendLine("## 1. Heightmap");
            sb.AppendLine();
            sb.AppendLine("In the Terrain Tool, `Manage` tab > `Import height map`, select `elevation.asc`.");
            sb.AppendLine("ASC is a lossless ESRI ASCII grid. The Enfusion terrain wants a power-of-two number of");
            sb.AppendLine("faces (e.g. 512 faces = 513 vertices); pick the terrain resolution that matches the grid above.");
            sb.AppendLine();

            sb.AppendLine("## 2. Surface mask & satellite");
            sb.AppendLine();
            sb.AppendLine("- `satmap.png`     : colour satellite image, use as the base colour / sat layer.");
            sb.AppendLine("- `surfacemask.png`: per-material id mask (one colour per ground material). Use it to drive");
            sb.AppendLine("  your terrain material layers. Reforger has no automatic mask import, so paint or set up");
            sb.AppendLine("  material layers using this image as reference.");
            sb.AppendLine();

            sb.AppendLine("## 3. Objects");
            sb.AppendLine();
            sb.AppendLine("Install the **Import Objects Extended** Workbench plugin");
            sb.AppendLine("(https://github.com/Til-Weimann/import-objects-extended): drop its `scripts` folder into your mod.");
            sb.AppendLine();
            sb.AppendLine("For each file in `objects/`, open the tool, set `DataPath` to the .csv and click `Place`.");
            sb.AppendLine("Lines use absolute world coordinates `PosX PosY PosZ Pitch Yaw Roll Scale` (Y is ASL elevation),");
            sb.AppendLine("so set `terrainSnapDistance` to -1 (no snap) unless you want objects re-snapped to terrain.");
            sb.AppendLine();
            sb.AppendLine("Lines that start with a `\"{GUID}...et\"` carry their own prefab. Lines without one (7 values)");
            sb.AppendLine("have no Reforger mapping yet: assign a prefab pool in the tool's `m_PrefabVariants` before placing");
            sb.AppendLine("that layer. Extend the mapping JSON to add prefabs (get a GUID from Resource Manager >");
            sb.AppendLine("right-click prefab > Copy resource name).");
            sb.AppendLine();

            sb.AppendLine("### Layers");
            sb.AppendLine();
            sb.AppendLine("| Layer | Objects |");
            sb.AppendLine("|-------|---------|");
            foreach (var layer in stats.LayerCounts.OrderBy(l => l.Key))
            {
                sb.AppendLine(FormattableString.Invariant($"| {layer.Key} | {layer.Value} |"));
            }
            sb.AppendLine(FormattableString.Invariant($"| **total** | **{stats.TotalObjects}** |"));
            sb.AppendLine();

            if (stats.UnmappedModels.Count > 0)
            {
                sb.AppendLine("### Unmapped models");
                sb.AppendLine();
                sb.AppendLine("These Arma 3 models have no Reforger prefab in the mapping (exported as pool-driven lines):");
                sb.AppendLine();
                sb.AppendLine("| Model | Count |");
                sb.AppendLine("|-------|-------|");
                foreach (var model in stats.UnmappedModels.OrderByDescending(m => m.Value))
                {
                    sb.AppendLine(FormattableString.Invariant($"| {model.Key} | {model.Value} |"));
                }
                sb.AppendLine();
            }

            sb.AppendLine("## Not exported yet");
            sb.AppendLine();
            sb.AppendLine("Roads, water bodies and material layer auto-setup are Arma-3 specific in this toolchain and are");
            sb.AppendLine("not part of the Reforger export. Recreate roads with the Road Tool inside the World Editor.");

            return sb.ToString();
        }
    }
}
